swagger: '2.0'
info:
  description: Atm service api Documentation
  version: '1.0'
  title: Atm service api Documentation
  termsOfService: 'urn:tos'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:9090'
basePath: /api/atm
paths:
  /v1/locations/{cityname}:
    get:
      tags:
        - location-controller
      summary: Fetches the atm locations by city name
      operationId: getAtmLocationUsingGET
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: cityname
          in: path
          description: cityname
          required: true
          type: string
      responses:
        '200':
          description: Successfully retrieved list
          schema:
            type: array
            items:
              $ref: '#/definitions/AtmLocation'
        '400':
          description: No Atms found in city
          schema:
            $ref: '#/definitions/ErrorResponse'
        '422':
          description: Unable to process the downstream service response
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
        '502':
          description: Error occurred while calling service
          schema:
            $ref: '#/definitions/ErrorResponse'
  /v1/locations:
    get:
      tags:
        - location-controller
      summary: 'fetches the list of atms available in locations '
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: Successfully retrieved list
          schema:
            type: array
            items:
              $ref: '#/definitions/AtmLocation'
        '400':
          description: No Atms found
          schema:
            $ref: '#/definitions/ErrorResponse'
        '422':
          description: Unable to process the downstream service response
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
        '502':
          description: Error occurred while calling service
          schema:
            $ref: '#/definitions/ErrorResponse'
definitions:
  Timings:
    type: object
    properties:
      hourFrom:
        type: string
      hourTo:
        type: string
  Address:
    type: object
    properties:
      city:
        type: string
      geoLocation:
        $ref: '#/definitions/GeoLocation'
      houseNumber:
        type: string
      postalCode:
        type: string
      street:
        type: string
  AtmLocation:
    type: object
    properties:
      address:
        $ref: '#/definitions/Address'
      distance:
        type: integer
        format: int64
      functionality:
        type: string
      openingHours:
        type: array
        items:
          $ref: '#/definitions/OpeningHours'
      type:
        type: string
  GeoLocation:
    type: object
    properties:
      latitude:
        type: string
      longitude:
        type: string
  OpeningHours:
    type: object
    properties:
      dayOfWeek:
        type: integer
        format: int32
      hoursList:
        type: array
        items:
          $ref: '#/definitions/Timings'
  ErrorResponse:
    type: object
    properties:
      message:
        type: string